# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bumprapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plate',
            name='downvotes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plate',
            name='first_recorded',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of first review'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plate',
            name='upvotes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plate',
            name='plate_text',
            field=models.CharField(max_length=8),
        ),
    ]
