# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bumprapp', '0002_auto_20170923_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='first_recorded',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of first review'),
        ),
    ]
