# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bumprapp', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plate',
            name='plate_text',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
