# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bumprapp', '0007_auto_20170928_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='plate',
            name='car_color',
            field=models.CharField(choices=[('WHI', 'White'), ('SIL', 'Silver'), ('GOL', 'Gold'), ('BLA', 'Black'), ('GRY', 'Grey'), ('BLU', 'Blue'), ('RED', 'Red'), ('BRO', 'Brown'), ('GRN', 'Green'), ('PUR', 'Purple'), ('UNS', 'Unknown Color')], default='UNS', max_length=3),
        ),
    ]
