# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bumprapp', '0008_plate_car_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='plate',
            name='claimed',
            field=models.BooleanField(default=False),
        ),
    ]
